--- #YAML:1.0
name:                Data-Dumper-Again
version:             0.0001
abstract:            An OO alter ego for Data::Dumper
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Carp:                          0
    Class::Accessor:               0
    Data::Dumper:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Adriano R. Ferreira <ferreira@cpan.org>
recommends:
    Test::Pod:                     1.18
    Test::Pod::Coverage:                    1.04
